### ISSUE TITLE
Alternative CPLD?

### ISSUE THREAD

**Issue by djbiohazard** [ClusterM/famicom-dumper-writer#3]
The EPM3064 seems to be EOL, is there any other alternative chip that could be used?

**Comment by ClusterM** [comment]
Yes, i think. But it's developed for EPM3064 and there is no pin-compatible alternatives :( Need to change schematic and board for  something else.

**Comment by ClusterM** [comment]
I think that it's possible to migrate to EPM7064AETC44, but it's very expensive.

**Comment by derchr** [comment]
Hello, is it possible to use EPM3064ATC44-10N instead of EPM3064ATC44-7 as the latter one is hardly available?

**Comment by ClusterM** [comment]
> Hello, is it possible to use EPM3064ATC44-10N instead of EPM3064ATC44-7 as the latter one is hardly available?

Hi! Yes, they are compatible as far as i can remember.

**Comment by derchr** [comment]
> > Hello, is it possible to use EPM3064ATC44-10N instead of EPM3064ATC44-7 as the latter one is hardly available?
> 
> Hi! Yes, they are compatible as far as i can remember.

Thanks!
