### ISSUE TITLE
Configuration of Altera EPM3064 cant' be updated

### ISSUE THREAD

**Issue by kolmogorovpavel** [ClusterM/famicom-dumper-writer#4]
After copying file FamicomDumper.svf to drive, led is always become red. After reconnecting drive the file is still there.

**Comment by Regle-Lin** [comment]
when I programmed the FamicomDumperBootloader.bin or FamicomDumper.bin to STM32 MCU by STLINK V2 and connect the dumper to USB, the device cannot recognize by PC(win10 64 bit), the PC showing unknow device, if anyone could give a guidance for how to make it work will be appreciated.

**Comment by kolmogorovpavel** [comment]
You just need to programm FamicomDumperBootloader.bin to STM32 MCU by STLINK V2. (Power dumper by usb) Then you should short 15 and 16 pin and connect to usb, then remove connection between 15 an 16 (you can see it in the video). The led become green first, then yellow and USB drive will be detected. You should format it before copying FamicomDumper.bin to the drive.

**Comment by Regle-Lin** [comment]
My dumper now working perfect! my problem is I'm used the oscillator(need provide vdd for work) not the crystal for STM32, so I need to re-soldering the right pin for let the 16M signal input from STM32 pin23.
in your case, maybe you need to check the ALTERA chip soldering if any shorted pin or mounted in wrong direction(such mistaken happened to me), if confirmed no any hardware issues, please try to update the FW one by one, try only the STM32 BIN first and then CPLD, when the CPLD FW updating, all the read/write LED is dim light and the CHR red LED will be solid light when the CPLD FW update done.

**Comment by kolmogorovpavel** [comment]
In my case dumper was bought maybe a year or two ago. So it has an old firmware. A updated bootloader first with stlink, then stm32 firmware by copying to 192kb drive. Dumper is working now, but I can't update CPLD. Maybe old pcb has some differences. But all tryes to copy svf ended up with red light of rgb led.

**Comment by Regle-Lin** [comment]
you can try to use the USB-BLASTER for the CPLD programming, but I'm suggest you to check the connection differences to the latest release of PCB layout.

**Comment by serperus** [comment]
> In my case dumper was bought maybe a year or two ago. So it has an old firmware. A updated bootloader first with stlink, then stm32 firmware by copying to 192kb drive. Dumper is working now, but I can't update CPLD. Maybe old pcb has some differences. But all tryes to copy svf ended up with red light of rgb led.

Try to copy to ubs flash both files together. Bin and svf at the same time.

**Comment by kolmogorovpavel** [comment]
> Try to copy to ubs flash both files together. Bin and svf at the same time.

That was the first that I've tried. With no luck.

**Comment by ClusterM** [comment]
> In my case dumper was bought maybe a year or two ago. So it has an old firmware. A updated bootloader first with stlink, then stm32 firmware by copying to 192kb drive. Dumper is working now, but I can't update CPLD. Maybe old pcb has some differences. But all tryes to copy svf ended up with red light of rgb led.

Hi. Which dumper revision you have? Only rev3.2+ has CPLD programming lines. So you can't update CPLD firmware via bootloader on old PCBs even with the latest bootloader.

**Comment by kolmogorovpavel** [comment]
Revision of my PCB is 2.1.
So it is clear now that I should use usb-blaster.
